<template>
    <SuperAdminLayout>
        <Head :title="'Edit: ' + article.title" />

        <div class="p-8">
            <div class="max-w-4xl">
                <div class="mb-8">
                    <Link 
                        :href="route('superadmin.articles.show', { website: currentWebsite?.id, article: article.id })" 
                        class="text-gray-400 hover:text-white flex items-center text-sm"
                    >
                        <svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
                        </svg>
                        Back to Article
                    </Link>
                </div>

                <!-- Success Message -->
                <div v-if="$page.props.flash?.success" class="bg-emerald-900/50 border border-emerald-500 text-emerald-200 px-6 py-4 rounded-lg mb-6">
                    <div class="flex items-center gap-3">
                        <svg class="w-5 h-5 text-emerald-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
                        </svg>
                        <span>{{ $page.props.flash.success }}</span>
                    </div>
                </div>

                <!-- AI Badge -->
                <div v-if="article.ai_generated" class="bg-gradient-to-r from-purple-900/30 to-indigo-900/30 border border-purple-800/50 rounded-lg p-4 mb-6">
                    <div class="flex items-center gap-3">
                        <div class="w-10 h-10 bg-gradient-to-br from-purple-500 to-indigo-600 rounded-lg flex items-center justify-center">
                            <svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z" />
                            </svg>
                        </div>
                        <div>
                            <h4 class="text-purple-300 font-medium">AI-Generated Article</h4>
                            <p class="text-sm text-purple-200/70">This article was generated by AI. Review and edit before publishing.</p>
                        </div>
                    </div>
                </div>

                <div class="bg-[#1a1a1a] rounded-2xl border border-[#2a2a2a] p-8">
                    <h1 class="text-3xl font-bold text-white mb-8">Edit Article</h1>

                    <form @submit.prevent="submit">
                        <!-- Category Selection -->
                        <div class="mb-6">
                            <label for="category_id" class="block text-sm font-medium text-gray-300 mb-2">
                                Category
                            </label>
                            <select
                                id="category_id"
                                v-model="form.category_id"
                                class="w-full bg-[#252525] border border-[#3a3a3a] text-white px-4 py-2 rounded-lg focus:outline-none focus:ring-2 focus:ring-emerald-500"
                            >
                                <option value="">Select a category</option>
                                <option v-for="category in currentWebsite?.categories" :key="category.id" :value="category.id">
                                    {{ category.name }}
                                </option>
                            </select>
                            <p v-if="form.errors.category_id" class="mt-2 text-sm text-red-500">{{ form.errors.category_id }}</p>
                        </div>

                        <!-- Article Type Selection -->
                        <div class="mb-6">
                            <label class="block text-sm font-medium text-gray-300 mb-2">
                                Article Type
                            </label>
                            <div class="grid grid-cols-2 gap-4">
                                <label 
                                    :class="[
                                        'flex items-center p-4 rounded-lg border-2 cursor-pointer transition-all',
                                        form.article_type === 'recipe' 
                                            ? 'border-emerald-500 bg-emerald-900/20' 
                                            : 'border-[#3a3a3a] hover:border-[#4a4a4a]'
                                    ]"
                                >
                                    <input type="radio" v-model="form.article_type" value="recipe" class="sr-only" />
                                    <div class="flex items-center gap-3">
                                        <div :class="['w-10 h-10 rounded-lg flex items-center justify-center', form.article_type === 'recipe' ? 'bg-emerald-500' : 'bg-[#3a3a3a]']">
                                            <svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" />
                                            </svg>
                                        </div>
                                        <div>
                                            <p class="text-white font-medium">Recipe</p>
                                            <p class="text-xs text-gray-400">URL: /recipes/slug</p>
                                        </div>
                                    </div>
                                </label>
                                <label 
                                    :class="[
                                        'flex items-center p-4 rounded-lg border-2 cursor-pointer transition-all',
                                        form.article_type === 'article' 
                                            ? 'border-emerald-500 bg-emerald-900/20' 
                                            : 'border-[#3a3a3a] hover:border-[#4a4a4a]'
                                    ]"
                                >
                                    <input type="radio" v-model="form.article_type" value="article" class="sr-only" />
                                    <div class="flex items-center gap-3">
                                        <div :class="['w-10 h-10 rounded-lg flex items-center justify-center', form.article_type === 'article' ? 'bg-emerald-500' : 'bg-[#3a3a3a]']">
                                            <svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 20H5a2 2 0 01-2-2V6a2 2 0 012-2h10a2 2 0 012 2v1m2 13a2 2 0 01-2-2V7m2 13a2 2 0 002-2V9a2 2 0 00-2-2h-2m-4-3H9M7 16h6M7 8h6v4H7V8z" />
                                            </svg>
                                        </div>
                                        <div>
                                            <p class="text-white font-medium">Article</p>
                                            <p class="text-xs text-gray-400">URL: /slug (root)</p>
                                        </div>
                                    </div>
                                </label>
                            </div>
                            <p class="mt-2 text-xs text-gray-500">Recipe articles appear at /recipes/slug, while regular articles appear directly at /slug</p>
                        </div>

                        <!-- Title -->
                        <div class="mb-6">
                            <label for="title" class="block text-sm font-medium text-gray-300 mb-2">
                                Title *
                            </label>
                            <input
                                id="title"
                                v-model="form.title"
                                type="text"
                                class="w-full bg-[#252525] border border-[#3a3a3a] text-white px-4 py-2 rounded-lg focus:outline-none focus:ring-2 focus:ring-emerald-500"
                                required
                            />
                            <p v-if="form.errors.title" class="mt-2 text-sm text-red-500">{{ form.errors.title }}</p>
                        </div>

                        <!-- Slug -->
                        <div class="mb-6">
                            <label for="slug" class="block text-sm font-medium text-gray-300 mb-2">
                                Slug (URL)
                            </label>
                            <input
                                id="slug"
                                v-model="form.slug"
                                type="text"
                                class="w-full bg-[#252525] border border-[#3a3a3a] text-white px-4 py-2 rounded-lg focus:outline-none focus:ring-2 focus:ring-emerald-500"
                            />
                            <p v-if="form.errors.slug" class="mt-2 text-sm text-red-500">{{ form.errors.slug }}</p>
                        </div>

                        <!-- Featured Image Upload -->
                        <div class="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
                            <ImageUpload
                                v-model="form.featured_image"
                                label="Featured Image"
                                type="article"
                                hint="Primary image shown on cards"
                                :allow-url="true"
                            />
                            <ImageUpload
                                v-model="form.secondary_image"
                                label="Secondary Image"
                                type="article"
                                hint="Middle of article image"
                                :allow-url="true"
                            />
                        </div>

                        <!-- Time Information -->
                        <div class="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
                            <div>
                                <label for="prep_time" class="block text-sm font-medium text-gray-300 mb-2">Prep Time</label>
                                <input id="prep_time" v-model="form.prep_time" type="text" class="w-full bg-[#252525] border border-[#3a3a3a] text-white px-4 py-2 rounded-lg focus:outline-none focus:ring-2 focus:ring-emerald-500" placeholder="e.g. 10 mins" />
                            </div>
                            <div>
                                <label for="cook_time" class="block text-sm font-medium text-gray-300 mb-2">Cook Time</label>
                                <input id="cook_time" v-model="form.cook_time" type="text" class="w-full bg-[#252525] border border-[#3a3a3a] text-white px-4 py-2 rounded-lg focus:outline-none focus:ring-2 focus:ring-emerald-500" placeholder="e.g. 20 mins" />
                            </div>
                            <div>
                                <label for="rest_time" class="block text-sm font-medium text-gray-300 mb-2">Rest Time</label>
                                <input id="rest_time" v-model="form.rest_time" type="text" class="w-full bg-[#252525] border border-[#3a3a3a] text-white px-4 py-2 rounded-lg focus:outline-none focus:ring-2 focus:ring-emerald-500" placeholder="e.g. 5 mins" />
                            </div>
                            <div>
                                <label for="total_time" class="block text-sm font-medium text-gray-300 mb-2">Total Time</label>
                                <input id="total_time" v-model="form.total_time" type="text" class="w-full bg-[#252525] border border-[#3a3a3a] text-white px-4 py-2 rounded-lg focus:outline-none focus:ring-2 focus:ring-emerald-500" placeholder="e.g. 35 mins" />
                            </div>
                        </div>

                        <!-- Excerpt -->
                        <div class="mb-6">
                            <label for="excerpt" class="block text-sm font-medium text-gray-300 mb-2">
                                Excerpt
                            </label>
                            <textarea
                                id="excerpt"
                                v-model="form.excerpt"
                                rows="3"
                                class="w-full bg-[#252525] border border-[#3a3a3a] text-white px-4 py-2 rounded-lg focus:outline-none focus:ring-2 focus:ring-emerald-500"
                                placeholder="A brief summary of the article..."
                            ></textarea>
                            <p v-if="form.errors.excerpt" class="mt-2 text-sm text-red-500">{{ form.errors.excerpt }}</p>
                        </div>

                        <!-- Content -->
                        <div class="mb-6">
                            <label for="content" class="block text-sm font-medium text-gray-300 mb-2">
                                Content *
                            </label>
                            <textarea
                                id="content"
                                v-model="form.content"
                                rows="15"
                                class="w-full bg-[#252525] border border-[#3a3a3a] text-white px-4 py-2 rounded-lg focus:outline-none focus:ring-2 focus:ring-emerald-500 font-mono text-sm"
                                placeholder="Write your article content here... (HTML supported)"
                                required
                            ></textarea>
                            <p class="mt-1 text-sm text-gray-500">You can use HTML for formatting.</p>
                            <p v-if="form.errors.content" class="mt-2 text-sm text-red-500">{{ form.errors.content }}</p>
                        </div>

                        <!-- Status -->
                        <div class="mb-6">
                            <label class="block text-sm font-medium text-gray-300 mb-2">
                                Status *
                            </label>
                            <div class="flex gap-6">
                                <label class="flex items-center cursor-pointer">
                                    <input type="radio" v-model="form.status" value="draft" class="mr-2 accent-emerald-500" />
                                    <span class="text-gray-300">Draft</span>
                                </label>
                                <label class="flex items-center cursor-pointer">
                                    <input type="radio" v-model="form.status" value="published" class="mr-2 accent-emerald-500" />
                                    <span class="text-gray-300">Published</span>
                                </label>
                                <label class="flex items-center cursor-pointer">
                                    <input type="radio" v-model="form.status" value="scheduled" class="mr-2 accent-emerald-500" />
                                    <span class="text-gray-300">Scheduled</span>
                                </label>
                            </div>
                            <p v-if="form.errors.status" class="mt-2 text-sm text-red-500">{{ form.errors.status }}</p>
                        </div>

                        <!-- Published At (for scheduled) -->
                        <div v-if="form.status === 'scheduled'" class="mb-6">
                            <label for="published_at" class="block text-sm font-medium text-gray-300 mb-2">
                                Publish Date
                            </label>
                            <input
                                id="published_at"
                                v-model="form.published_at"
                                type="datetime-local"
                                class="w-full bg-[#252525] border border-[#3a3a3a] text-white px-4 py-2 rounded-lg focus:outline-none focus:ring-2 focus:ring-emerald-500"
                            />
                            <p v-if="form.errors.published_at" class="mt-2 text-sm text-red-500">{{ form.errors.published_at }}</p>
                        </div>

                        <!-- Submit Buttons -->
                        <div class="flex items-center justify-between">
                            <button
                                type="button"
                                @click="deleteArticle"
                                class="px-6 py-2 text-red-400 hover:text-red-300 transition"
                            >
                                Delete Article
                            </button>
                            <div class="flex gap-4">
                                <Link
                                    :href="route('superadmin.articles.show', { website: currentWebsite?.id, article: article.id })"
                                    class="px-6 py-2 text-gray-400 hover:text-white transition"
                                >
                                    Cancel
                                </Link>
                                <button
                                    type="submit"
                                    :disabled="form.processing"
                                    class="px-6 py-3 bg-emerald-500 text-white font-semibold rounded-lg hover:bg-emerald-600 transition disabled:opacity-50 disabled:cursor-not-allowed"
                                >
                                    <span v-if="form.processing">Saving...</span>
                                    <span v-else>Save Changes</span>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </SuperAdminLayout>
</template>

<script setup>
import { computed } from 'vue';
import { Head, Link, useForm, router, usePage } from '@inertiajs/vue3';
import SuperAdminLayout from '@/Layouts/SuperAdminLayout.vue';
import ImageUpload from '@/Components/ImageUpload.vue';

const page = usePage();

const props = defineProps({
    article: Object,
    currentWebsite: Object,
    websites: Array
});

const form = useForm({
    category_id: props.article.category_id || '',
    title: props.article.title || '',
    slug: props.article.slug || '',
    excerpt: props.article.excerpt || '',
    content: props.article.content || '',
    featured_image: props.article.featured_image || '',
    secondary_image: props.article.secondary_image || '',
    prep_time: props.article.prep_time || '',
    cook_time: props.article.cook_time || '',
    rest_time: props.article.rest_time || '',
    total_time: props.article.total_time || '',
    status: props.article.status || 'draft',
    article_type: props.article.article_type || 'recipe',
    published_at: props.article.published_at ? props.article.published_at.substring(0, 16) : ''
});

const submit = () => {
    form.put(route('superadmin.articles.update', { 
        website: props.currentWebsite?.id, 
        article: props.article.id 
    }));
};

const deleteArticle = () => {
    if (confirm(`Are you sure you want to delete "${props.article.title}"?`)) {
        router.delete(route('superadmin.articles.destroy', { 
            website: props.currentWebsite?.id, 
            article: props.article.id 
        }));
    }
};
</script>
